"""image_column

Revision ID: 8bbed05c771c
Revises: 31c565ebb815
Create Date: 2025-10-04 17:27:44.788746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbed05c771c'
down_revision: Union[str, Sequence[str], None] = '31c565ebb815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Places', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Places', 'image_url')
    # ### end Alembic commands ###
